package dev.amenhancer.module.lyrics.online

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Pins QQ's QRC envelope to bytes captured from a real `GetPlayLyricInfo`
 * response ([QmRealEnvelopeFixture]), so the cipher is checked against what the
 * device actually receives rather than against an envelope generated by the
 * cipher under test.
 *
 * The accompanying structural cases parse plain QRC strings, so a parser change
 * is separated from a cipher change.
 */
class QrcParserTest {

    @Test
    fun `decrypts the real QQ QRC envelope into the xml body`() {
        val decrypted = QmCrypto.decryptQrc(QmRealEnvelopeFixture.LYRIC_HEX)

        assertTrue(decrypted.contains("<Lyric_1 LyricType="))
        assertTrue(decrypted.contains("初音ミク (初音未来)"))
        assertTrue(decrypted.contains("[0,1120]魔(0,46)法(46,46)"))
    }

    @Test
    fun `decrypts the real QQ translation envelope into plain lrc`() {
        val decrypted = QmCrypto.decryptQrc(QmRealEnvelopeFixture.TRANS_HEX)

        assertTrue(decrypted.contains("[ti:魔法みたいなミュージック!]"))
        assertTrue(decrypted.contains("[00:01.12]一二三 改变世界"))
    }

    @Test
    fun `an empty or non-hex envelope decrypts to nothing`() {
        assertEquals("", QmCrypto.decryptQrc(""))
        assertEquals("", QmCrypto.decryptQrc("  "))
        assertEquals("", QmCrypto.decryptQrc("zzzz"))
        assertEquals("", QmCrypto.decryptQrc("00"))
    }

    @Test
    fun `parses QRC words and keeps the line span`() {
        val result = QrcParser.parse(QRC_XML_BODY)

        assertEquals(2, result.original.size)
        assertEquals(0L, result.original[0].start)
        assertEquals(152L, result.original[0].end)

        // HLE's cursor-based word loop leaves the leading pre-marker text as a
        // zero-width word at the line start and a zero-width tail word at the
        // line end; the port keeps both so the two parse identically.
        val first = result.original[0].words
        assertEquals(listOf("金", "童", "子", ""), first.map(LyricsWord::text))
        assertEquals(0L, first[0].start)
        assertEquals(0L, first[0].end)
        assertEquals(0L, first[1].start)
        assertEquals(50L, first[1].end)
        assertEquals(50L, first[2].start)
        assertEquals(100L, first[2].end)
        assertEquals(100L, first[3].start)
        assertEquals(152L, first[3].end)

        val second = result.original[1].words
        assertEquals(listOf("遗", "憾", "要", "告", "诉", "你", ""), second.map(LyricsWord::text))
        assertEquals(730L, second[1].start)
        assertEquals(946L, second[1].end)
        assertEquals(1754L, second[5].start)
        assertEquals(2003L, second[5].end)
        assertEquals(2003L, second[6].start)
        assertEquals(2547L, second[6].end)
    }

    @Test
    fun `parses QQ QRC romanization instead of treating it as LRC`() {
        val result = QrcParser.parse(
            original = QRC_XML_BODY,
            romanization = QRC_ROMANIZATION_XML,
        )

        val romanization = result.romanization!!
        assertEquals(2, romanization.size)
        assertEquals(730L, romanization[1].start)
        assertEquals(
            "wai han yiu gou sou nei",
            romanization[1].words.joinToString("") { it.text },
        )
    }

    @Test
    fun `keeps plain LRC auxiliary lyrics compatible`() {
        val result = QrcParser.parse(
            original = QRC_BARE_LINE,
            translated = "[00:00.730]遗憾要告诉你",
            romanization = "[00:00.730]wai han yiu gou sou nei",
        )

        assertEquals("遗憾要告诉你", result.translated!!.single().words.single().text)
        assertEquals("wai han yiu gou sou nei", result.romanization!!.single().words.single().text)
    }

    @Test
    fun `inserts one space between QRC pronunciation units`() {
        val result = QrcParser.parse(
            original = QRC_BARE_LINE,
            romanization = QRC_BARE_ROMANIZATION,
        )

        assertEquals(
            "wai han yiu gou sou nei",
            result.romanization!!.single().words.single().text,
        )
    }

    @Test
    fun `a plain LRC body is parsed through the LRC fallback`() {
        val result = QrcParser.parse(
            original = "[00:00.730]遗憾要告诉你",
            type = "lrc",
        )

        assertEquals(1, result.original.size)
        assertEquals(730L, result.original.single().start)
    }

    @Test
    fun `an empty body yields a result with no lines`() {
        val result = QrcParser.parse(original = null)

        assertTrue(result.original.isEmpty())
        assertEquals(null, result.translated)
        assertEquals(null, result.romanization)
    }

    private companion object {
        /** `[730,1817]遗(730,216)…你(2003,544)` without the XML envelope. */
        const val QRC_BARE_LINE =
            "[730,1817]遗(730,216)憾(946,240)要(1186,305)告(1491,263)诉(1754,249)你(2003,544)"

        const val QRC_BARE_ROMANIZATION =
            "[730,1817]wai(730,216)han(946,240)yiu(1186,305)gou(1491,263)sou(1754,249)nei(2003,544)"

        /** The two-line QRC XML body the old structural cases were written around. */
        const val QRC_XML_BODY =
            "<Lyric_1 LyricType=\"1\" LyricContent=\"" +
                "[0,152]金(0,50)童(50,50)子(100,52)\n" +
                "$QRC_BARE_LINE\"/>"

        const val QRC_ROMANIZATION_XML =
            "<Lyric_1 LyricType=\"1\" LyricContent=\"" +
                "[0,152]jin(0,50)tong(50,50)zi(100,52)\n" +
                "$QRC_BARE_ROMANIZATION\"/>"
    }
}
